from __future__ import annotations

import argparse
import re
import shutil
import subprocess
from datetime import UTC, datetime
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_ROOT = REPO_ROOT / "build" / "triage"
MARKER = ".mergeproof-triage-workspace"
RUN_CONTEXT = "MERGEPROOF_RUN_CONTEXT.yaml"
CASE_IDS = tuple(f"TRIAGE-{index:03d}" for index in range(1, 9))
BOB_MANIFEST = Path(".bob/manifest.yaml")
FEATURE_SCHEMA = Path(
    "docs/05_PREPRODUCTION/01_CONTRACTS_ACTIVE/FEATURE_SCHEMA_FINAL.yaml"
)
OUTPUT_ADDENDUM = Path(
    "docs/05_PREPRODUCTION/01_CONTRACTS_ACTIVE/"
    "OUTPUT_AND_RUN_RECORD_ADDENDUM_v1.1.md"
)
SOURCE_ID_PATTERN = re.compile(
    r"^\s*-\s*Source ID:\s*\`?([^\`\s]+)\`?\s*$",
    re.MULTILINE,
)

COMMON_PATHS = (
    Path(".bob"),
    Path("docs/03_EVALUATION_AND_DOMAIN_RULES/domain_rules_v1.0.yaml"),
    FEATURE_SCHEMA,
    OUTPUT_ADDENDUM,
    Path("schemas/mergeproof_report.schema.json"),
)


def _git_head() -> str:
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    sha = result.stdout.strip()
    if result.returncode != 0 or not sha:
        raise RuntimeError("Unable to resolve repository commit SHA.")
    return sha


def _load_yaml(path: Path) -> dict:
    payload = yaml.safe_load((REPO_ROOT / path).read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise RuntimeError(f"Expected mapping in {path}.")
    return payload


def _case_root(case_id: str) -> Path:
    return Path("eval") / "fixtures" / case_id


def _case_descriptor(case_id: str) -> Path:
    return _case_root(case_id) / "case.yaml"


def _validate_case_paths(case_id: str, case: dict) -> None:
    root = _case_root(case_id)
    candidates = [
        *case["source_files"],
        *case["changed_files"],
        case["application_entrypoint"],
    ]
    for raw_path in candidates:
        relative = Path(raw_path)
        try:
            relative.relative_to(root)
        except ValueError as exc:
            raise RuntimeError(
                f"{case_id} path escapes its fixture root: {raw_path}"
            ) from exc
        if not (REPO_ROOT / relative).is_file():
            raise RuntimeError(f"{case_id} references missing file: {raw_path}")


def _source_ids(case: dict) -> list[str]:
    source_ids: list[str] = []
    for raw_path in case["source_files"]:
        text = (REPO_ROOT / raw_path).read_text(encoding="utf-8")
        matches = SOURCE_ID_PATTERN.findall(text)
        if not matches:
            raise RuntimeError(f"No Source ID metadata found in {raw_path}.")
        for source_id in matches:
            if source_id not in source_ids:
                source_ids.append(source_id)
    return source_ids


def _copy(source: Path, output: Path) -> None:
    src = REPO_ROOT / source
    dst = output / source
    dst.parent.mkdir(parents=True, exist_ok=True)
    if src.is_dir():
        shutil.copytree(src, dst)
    else:
        shutil.copy2(src, dst)


def _reset(output: Path) -> None:
    if not output.exists():
        return
    if not (output / MARKER).is_file():
        raise RuntimeError(
            f"Refusing to replace {output}: generated-workspace marker is missing."
        )
    shutil.rmtree(output)


def _prepare(case_id: str, output_root: Path) -> Path:
    descriptor = _case_descriptor(case_id)
    case = _load_yaml(descriptor)
    if case.get("case_id") != case_id:
        raise RuntimeError(f"{descriptor} case_id does not match {case_id}.")
    _validate_case_paths(case_id, case)

    manifest = _load_yaml(BOB_MANIFEST)
    feature_schema = _load_yaml(FEATURE_SCHEMA)
    commit_sha = _git_head()
    timestamp = datetime.now(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")

    output = (output_root / case_id).resolve()
    _reset(output)
    output.mkdir(parents=True, exist_ok=True)
    (output / MARKER).write_text(
        "generated by prepare_triage_workspace.py\n",
        encoding="utf-8",
    )

    for path in COMMON_PATHS:
        _copy(path, output)
    _copy(_case_root(case_id), output)

    context = {
        "workspace_version": "1.1",
        "run_id": f"mergeproof-{case_id.lower()}-{commit_sha[:12]}-"
        f"{timestamp.replace(':', '')}",
        "case_id": case_id,
        "repository_commit_sha": commit_sha,
        "changed_files": list(case["changed_files"]),
        "source_ids": _source_ids(case),
        "bob_mode_version": str(manifest["bob_mode"]["version"]),
        "skill_version": str(manifest["skill"]["version"]),
        "timestamp": timestamp,
        "report_schema_version": str(feature_schema["version"]),
        "case_descriptor": descriptor.as_posix(),
        "report_schema": "schemas/mergeproof_report.schema.json",
        "domain_rules": "docs/03_EVALUATION_AND_DOMAIN_RULES/domain_rules_v1.0.yaml",
        "output_contract_addendum": OUTPUT_ADDENDUM.as_posix(),
    }
    (output / RUN_CONTEXT).write_text(
        yaml.safe_dump(context, sort_keys=False),
        encoding="utf-8",
    )
    return output


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Prepare isolated IBM Bob workspaces for frozen TRIAGE cases."
    )
    target = parser.add_mutually_exclusive_group(required=True)
    target.add_argument("--case", choices=CASE_IDS)
    target.add_argument("--all", action="store_true")
    parser.add_argument("--output-root", type=Path, default=DEFAULT_OUTPUT_ROOT)
    args = parser.parse_args()

    cases = CASE_IDS if args.all else (args.case,)
    for case_id in cases:
        output = _prepare(case_id, args.output_root)
        print(f"[PASS] {case_id}: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
