from __future__ import annotations

import argparse
import re
import shutil
import subprocess
from datetime import UTC, datetime
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = REPO_ROOT / "build" / "demo-workspace"
MARKER = ".mergeproof-demo-workspace"
RUN_CONTEXT = "MERGEPROOF_RUN_CONTEXT.yaml"
CASE_DESCRIPTOR = Path("demo/case.yaml")
BOB_MANIFEST = Path(".bob/manifest.yaml")
FEATURE_SCHEMA = Path(
    "docs/05_PREPRODUCTION/01_CONTRACTS_ACTIVE/FEATURE_SCHEMA_FINAL.yaml"
)
OUTPUT_ADDENDUM = Path(
    "docs/05_PREPRODUCTION/01_CONTRACTS_ACTIVE/"
    "OUTPUT_AND_RUN_RECORD_ADDENDUM_v1.1.md"
)
SOURCE_ID_PATTERN = re.compile(
    r"^\s*-\s*Source ID:\s*`?([^`\s]+)`?\s*$",
    re.MULTILINE,
)

COPY_PATHS = (
    Path(".bob"),
    Path("demo"),
    Path("docs/03_EVALUATION_AND_DOMAIN_RULES/domain_rules_v1.0.yaml"),
    FEATURE_SCHEMA,
    OUTPUT_ADDENDUM,
    Path("schemas/mergeproof_report.schema.json"),
)


def _repository_commit_sha() -> str:
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    commit_sha = result.stdout.strip()
    if result.returncode != 0 or not commit_sha:
        raise RuntimeError("Unable to resolve repository commit SHA for demo run context.")
    return commit_sha


def _load_yaml(path: Path) -> dict:
    value = yaml.safe_load((REPO_ROOT / path).read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise RuntimeError(f"Expected mapping in {path}.")
    return value


def _source_ids(case: dict) -> list[str]:
    source_ids: list[str] = []
    for relative_path in case["source_files"]:
        text = (REPO_ROOT / relative_path).read_text(encoding="utf-8")
        match = SOURCE_ID_PATTERN.search(text)
        if match is None:
            raise RuntimeError(f"Unable to resolve source ID from {relative_path}.")
        source_ids.append(match.group(1))
    return source_ids


def _run_context() -> dict:
    commit_sha = _repository_commit_sha()
    timestamp = datetime.now(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    case = _load_yaml(CASE_DESCRIPTOR)
    manifest = _load_yaml(BOB_MANIFEST)
    feature_schema = _load_yaml(FEATURE_SCHEMA)

    return {
        "workspace_version": "1.1",
        "run_id": f"mergeproof-{commit_sha[:12]}-{timestamp.replace(':', '')}",
        "repository_commit_sha": commit_sha,
        "changed_files": list(case["changed_files"]),
        "source_ids": _source_ids(case),
        "bob_mode_version": str(manifest["bob_mode"]["version"]),
        "skill_version": str(manifest["skill"]["version"]),
        "timestamp": timestamp,
        "report_schema_version": str(feature_schema["version"]),
        "case_descriptor": CASE_DESCRIPTOR.as_posix(),
        "report_schema": "schemas/mergeproof_report.schema.json",
        "domain_rules": "docs/03_EVALUATION_AND_DOMAIN_RULES/domain_rules_v1.0.yaml",
        "output_contract_addendum": OUTPUT_ADDENDUM.as_posix(),
    }


def _reset_output(output: Path) -> None:
    if not output.exists():
        return
    marker = output / MARKER
    if not marker.exists():
        raise RuntimeError(
            f"Refusing to replace {output}: generated-workspace marker is missing."
        )
    shutil.rmtree(output)


def _copy_path(source: Path, output: Path) -> None:
    destination = output / source
    destination.parent.mkdir(parents=True, exist_ok=True)
    absolute_source = REPO_ROOT / source
    if absolute_source.is_dir():
        shutil.copytree(absolute_source, destination)
    else:
        shutil.copy2(absolute_source, destination)


def prepare_workspace(output: Path) -> Path:
    output = output.resolve()
    _reset_output(output)
    output.mkdir(parents=True, exist_ok=True)
    (output / MARKER).write_text("generated by prepare_demo_workspace.py\n", encoding="utf-8")
    for source in COPY_PATHS:
        _copy_path(source, output)
    (output / RUN_CONTEXT).write_text(
        yaml.safe_dump(_run_context(), sort_keys=False),
        encoding="utf-8",
    )
    return output


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Build an analysis-only Bob workspace for the seeded demo."
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    output = prepare_workspace(args.output)
    print(f"[PASS] prepared isolated demo workspace at {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
