from __future__ import annotations

import argparse
import shutil
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = REPO_ROOT / "build" / "demo-workspace"
MARKER = ".mergeproof-demo-workspace"

COPY_PATHS = (
    Path(".bob"),
    Path("demo"),
    Path("docs/03_EVALUATION_AND_DOMAIN_RULES/domain_rules_v1.0.yaml"),
    Path("docs/05_PREPRODUCTION/01_CONTRACTS_ACTIVE/FEATURE_SCHEMA_FINAL.yaml"),
    Path("schemas/mergeproof_report.schema.json"),
)


def _reset_output(output: Path) -> None:
    if not output.exists():
        return

    marker = output / MARKER
    if not marker.exists():
        raise RuntimeError(
            f"Refusing to replace {output}: generated-workspace marker is missing."
        )
    shutil.rmtree(output)


def _copy_path(source: Path, output: Path) -> None:
    destination = output / source
    destination.parent.mkdir(parents=True, exist_ok=True)

    absolute_source = REPO_ROOT / source
    if absolute_source.is_dir():
        shutil.copytree(absolute_source, destination)
    else:
        shutil.copy2(absolute_source, destination)


def prepare_workspace(output: Path) -> Path:
    output = output.resolve()
    _reset_output(output)
    output.mkdir(parents=True, exist_ok=True)
    (output / MARKER).write_text("generated by prepare_demo_workspace.py\n", encoding="utf-8")

    for source in COPY_PATHS:
        _copy_path(source, output)

    return output


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Build an analysis-only Bob workspace for the seeded demo."
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    output = prepare_workspace(args.output)
    print(f"[PASS] prepared isolated demo workspace at {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
